### ISSUE TITLE
Misc. Change requests

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org#91]
#### 1. margins on blog posts

Reviewing #90 I noticed that the margins on blog post are rather large. For example, here's how they look look on an iPhone SE:

![Screenshot 2024-03-06 at 6 47 06 PM](https://github.com/okTurtles/groupincome.org/assets/138706/c16d26e8-c900-491a-ba95-5b74142874dd)

I think the okTurtles blog uses perfect margins on this size display:

![Screenshot 2024-03-06 at 6 46 32 PM](https://github.com/okTurtles/groupincome.org/assets/138706/044c2378-1f67-492e-a4a4-c81bb26a4fa8)

#### 2. Lists are not indented

![Screenshot 2024-03-06 at 6 45 11 PM](https://github.com/okTurtles/groupincome.org/assets/138706/224cb841-c57c-4a84-92ee-6d55bb6ac3ea)

While we don't need to make the indents as pronounced, I think it looks better with them (as on the old blog):

![Screenshot 2024-03-06 at 6 45 15 PM](https://github.com/okTurtles/groupincome.org/assets/138706/096011ce-62f6-44ec-89e6-b959bd43c41d)

Note: when adjusting these, make sure to check how they look on mobile. Lists should still be indented on mobile too, but it shouldn't be as pronounced as on desktop due to the smaller screen width (so they should be proportionally scaled down).

#### 3. Blog links on mobile

On mobile, there is no "on hover" concept. So blog links stand out less:

![Screenshot 2024-03-06 at 6 52 07 PM](https://github.com/okTurtles/groupincome.org/assets/138706/45c13406-d52e-4582-ab4f-992d3bfe8f7d)

Perhaps this is a matter of taste, but what about making the links underlined always, and performing some other effect on hover (like making the color different)?

![Screenshot 2024-03-06 at 6 52 13 PM](https://github.com/okTurtles/groupincome.org/assets/138706/132d0c37-1e03-4c65-9312-bca1d5af5b87)

#### 4. Sans Serif Font

Maybe I'm just used to how the old blog looked, but I quite like the font we used on it, it looks more academic and professional to me. I also like how the section headers have slightly visible underlines under them to separate the different sections more:

![Screenshot 2024-03-14 at 5 18 29 PM](https://github.com/okTurtles/groupincome.org/assets/138706/fa7934ce-b637-4408-bea4-6537727e2567)

Here's the new one:

![Screenshot 2024-03-06 at 6 55 07 PM](https://github.com/okTurtles/groupincome.org/assets/138706/23a5039f-b755-4ff7-8c5d-01c7fd75898a)

I wonder what the blog would look like with this type of font? Does it make sense to use it or stick with the one we have? I'm wondering what your opinion on this is @SebinSong.

### Solution

Go through the above issues and make a PR for the problems that are clear problems, and make it easy to uncomment/comment out the font change to see what would look better. Also wondering what your opinion is (what do you think would make it look better)?

**Comment by SebinSong** [comment]
@taoeffect Am looking at the No **4.** of the above comment, and it wasn't clear because the two screenshots attached look the same. But did you mean the font-family used in [this page](https://blog.okturtles.org/2016/09/how-to-compromise-zcash-and-take-over-the-world/) and the slight underline used in the blue box below?

<img src='https://github.com/okTurtles/groupincome.org/assets/17641213/916b365d-2781-44d1-992c-f9b43253adac' width='480'>


EDIT:
While waiting on your reply, I went ahead and made some changes and I agree that the section title having a slight underline makes the article look more organised. (A screenshot below)
 
<img src='https://github.com/okTurtles/groupincome.org/assets/17641213/1afc5793-c107-445e-93f7-f6a3abbf90a2' width='480'>

Regarding using another font for the blog post, I _personally_ think a website feels more pleasant when a single font-family used across the entire website.

I myself actually recently built [a booking website](https://www.ilwolbooking.com/) and this is an example where I used multiple fonts. It currently has this rather minor issue where one font (almost always) loads earlier than the other and that makes the text presentation of the website abruptly changes upon the completion of the second font, which isn't that pleasant user experience.

Also, I think the blog post looks clean and fine with the current font, but it's just my personal opinion :)

**Comment by taoeffect** [comment]
> @taoeffect Am looking at the No 4. of the above comment, and it wasn't clear because the two screenshots attached look the same. But did you mean the font-family used in [this page](https://blog.okturtles.org/2016/09/how-to-compromise-zcash-and-take-over-the-world/) and the slight underline used in the blue box below?

*checks my own post*

_\*thinks, "Did I **** that up? I ****'d that up"_

Nice catch @SebinSong, indeed I uploaded the same picture twice. Fixed!

> Regarding using another font for the blog post, I personally think a website feels more pleasant when a single font-family used across the entire website.

OK, we can keep the current font 👍

**Comment by SebinSong** [comment]
@taoeffect 
*thinks, "Did I **** that up? I ****'d that up"

what is this btw...?

**Comment by taoeffect** [comment]
> what is this btw...?

That was me attempting to be funny 😅

**Comment by SebinSong** [comment]
@taoeffect Oh haha, I somehow interpreted it that you got mad and cursing at me lol. The PR for this issue is now ready btw!
